# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.email_list_response import EmailListResponse

class TestEmailListResponse(unittest.TestCase):
    """EmailListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailListResponse:
        """Test EmailListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailListResponse`
        """
        model = EmailListResponse()
        if include_optional:
            return EmailListResponse(
                emails = [
                    goodsender.models.email_account.EmailAccount(
                        email = 'user@example.com', 
                        name = 'Jane Doe', 
                        domain = 'example.com', 
                        consent_status = 'pending', 
                        engagement_status = 'new', )
                    ],
                next_cursor = 'eyJjcmVhdGVkQXRNaWNyb3MiOjE2ODAxMjM0NTY3ODksImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSJ9'
            )
        else:
            return EmailListResponse(
                emails = [
                    goodsender.models.email_account.EmailAccount(
                        email = 'user@example.com', 
                        name = 'Jane Doe', 
                        domain = 'example.com', 
                        consent_status = 'pending', 
                        engagement_status = 'new', )
                    ],
        )
        """

    def testEmailListResponse(self):
        """Test EmailListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
