# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.domain import Domain

class TestDomain(unittest.TestCase):
    """Domain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Domain:
        """Test Domain
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Domain`
        """
        model = Domain()
        if include_optional:
            return Domain(
                domain = 'example.com',
                tracking = 'track.example.com',
                return_path = 'bounces.example.com',
                require_tls = True,
                verification = goodsender.models.domain_verification.DomainVerification(
                    verified = True, 
                    tracking_verified = True, 
                    return_path_verified = True, 
                    dkim1_verified = True, 
                    dkim2_verified = True, )
            )
        else:
            return Domain(
                domain = 'example.com',
                tracking = 'track.example.com',
                return_path = 'bounces.example.com',
                require_tls = True,
                verification = goodsender.models.domain_verification.DomainVerification(
                    verified = True, 
                    tracking_verified = True, 
                    return_path_verified = True, 
                    dkim1_verified = True, 
                    dkim2_verified = True, ),
        )
        """

    def testDomain(self):
        """Test Domain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
