# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.template_email_request import TemplateEmailRequest

class TestTemplateEmailRequest(unittest.TestCase):
    """TemplateEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateEmailRequest:
        """Test TemplateEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateEmailRequest`
        """
        model = TemplateEmailRequest()
        if include_optional:
            return TemplateEmailRequest(
                var_from = goodsender.models.address.Address(
                    email = '', 
                    name = '', ),
                to = goodsender.models.address.Address(
                    email = '', 
                    name = '', ),
                subject = '0',
                template = goodsender.models.template_email_request_template.TemplateEmailRequest_template(
                    template_id = '', 
                    variables = {
                        'key' : ''
                        }, )
            )
        else:
            return TemplateEmailRequest(
                var_from = goodsender.models.address.Address(
                    email = '', 
                    name = '', ),
                to = goodsender.models.address.Address(
                    email = '', 
                    name = '', ),
                subject = '0',
                template = goodsender.models.template_email_request_template.TemplateEmailRequest_template(
                    template_id = '', 
                    variables = {
                        'key' : ''
                        }, ),
        )
        """

    def testTemplateEmailRequest(self):
        """Test TemplateEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
