# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.send_email_response import SendEmailResponse

class TestSendEmailResponse(unittest.TestCase):
    """SendEmailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailResponse:
        """Test SendEmailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailResponse`
        """
        model = SendEmailResponse()
        if include_optional:
            return SendEmailResponse(
                sent = 8,
                declined = 2
            )
        else:
            return SendEmailResponse(
                sent = 8,
                declined = 2,
        )
        """

    def testSendEmailResponse(self):
        """Test SendEmailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
