# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.quota_exceeded_error import QuotaExceededError

class TestQuotaExceededError(unittest.TestCase):
    """QuotaExceededError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuotaExceededError:
        """Test QuotaExceededError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuotaExceededError`
        """
        model = QuotaExceededError()
        if include_optional:
            return QuotaExceededError(
                code = 'quota_exceeded',
                kind = 'daily',
                message = '',
                limit = 56,
                used = 56,
                reset_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return QuotaExceededError(
                code = 'quota_exceeded',
                kind = 'daily',
                message = '',
                limit = 56,
                used = 56,
                reset_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testQuotaExceededError(self):
        """Test QuotaExceededError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
