# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.api.emails_api import EmailsApi


class TestEmailsApi(unittest.TestCase):
    """EmailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailsApi()

    def tearDown(self) -> None:
        pass

    def test_get_email_consent_status(self) -> None:
        """Test case for get_email_consent_status

        Get recipient consent status
        """
        pass

    def test_list_email_consents(self) -> None:
        """Test case for list_email_consents

        List email consent statuses
        """
        pass

    def test_request_email_consent(self) -> None:
        """Test case for request_email_consent

        Request recipients' consent to receive emails from your domain
        """
        pass

    def test_send_email(self) -> None:
        """Test case for send_email

        Send an email or a batch of emails
        """
        pass

    def test_send_template_email(self) -> None:
        """Test case for send_template_email

        Send a transactional email using a template
        """
        pass


if __name__ == '__main__':
    unittest.main()
