# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.send_email_request import SendEmailRequest

class TestSendEmailRequest(unittest.TestCase):
    """SendEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailRequest:
        """Test SendEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailRequest`
        """
        model = SendEmailRequest()
        if include_optional:
            return SendEmailRequest(
                emails = [
                    goodsender.models.send_email.SendEmail(
                        from = null, 
                        to = [
                            goodsender.models.address.Address(
                                email = '', 
                                name = '', )
                            ], 
                        subject = '', 
                        text_content = '', 
                        html_content = '', 
                        markdown_content = '0', 
                        template_id = '', 
                        template_data = { }, 
                        attachments = [
                            goodsender.models.attachment.Attachment(
                                file_name = '', 
                                content = 'YQ==', 
                                content_type = '', 
                                inline_id = '', )
                            ], 
                        headers = {
                            'key' : ''
                            }, 
                        reply_to = null, 
                        send_time = 56, 
                        webhook_data = {
                            'key' : ''
                            }, 
                        tag = '', 
                        tracking = null, )
                    ]
            )
        else:
            return SendEmailRequest(
                emails = [
                    goodsender.models.send_email.SendEmail(
                        from = null, 
                        to = [
                            goodsender.models.address.Address(
                                email = '', 
                                name = '', )
                            ], 
                        subject = '', 
                        text_content = '', 
                        html_content = '', 
                        markdown_content = '0', 
                        template_id = '', 
                        template_data = { }, 
                        attachments = [
                            goodsender.models.attachment.Attachment(
                                file_name = '', 
                                content = 'YQ==', 
                                content_type = '', 
                                inline_id = '', )
                            ], 
                        headers = {
                            'key' : ''
                            }, 
                        reply_to = null, 
                        send_time = 56, 
                        webhook_data = {
                            'key' : ''
                            }, 
                        tag = '', 
                        tracking = null, )
                    ],
        )
        """

    def testSendEmailRequest(self):
        """Test SendEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
