# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.consent_email_request import ConsentEmailRequest

class TestConsentEmailRequest(unittest.TestCase):
    """ConsentEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsentEmailRequest:
        """Test ConsentEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsentEmailRequest`
        """
        model = ConsentEmailRequest()
        if include_optional:
            return ConsentEmailRequest(
                domain = 'example.com',
                redirect_url = 'https://example.com/consent/{email}',
                emails = [user1@example.com, {email=user2@example.com, name=Jane Doe}]
            )
        else:
            return ConsentEmailRequest(
                domain = 'example.com',
                emails = [user1@example.com, {email=user2@example.com, name=Jane Doe}],
        )
        """

    def testConsentEmailRequest(self):
        """Test ConsentEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
