# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.tracking_settings import TrackingSettings

class TestTrackingSettings(unittest.TestCase):
    """TrackingSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackingSettings:
        """Test TrackingSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrackingSettings`
        """
        model = TrackingSettings()
        if include_optional:
            return TrackingSettings(
                opens = True,
                clicks = True,
                unsubscribes = True,
                unsubscribe_group_id = 56
            )
        else:
            return TrackingSettings(
        )
        """

    def testTrackingSettings(self):
        """Test TrackingSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
