# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from goodsender.models.domain_list_response import DomainListResponse

class TestDomainListResponse(unittest.TestCase):
    """DomainListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainListResponse:
        """Test DomainListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainListResponse`
        """
        model = DomainListResponse()
        if include_optional:
            return DomainListResponse(
                domains = [
                    goodsender.models.domain.Domain(
                        domain = 'example.com', 
                        tracking = 'track.example.com', 
                        return_path = 'bounces.example.com', 
                        require_tls = True, 
                        verification = goodsender.models.domain_verification.DomainVerification(
                            verified = True, 
                            tracking_verified = True, 
                            return_path_verified = True, 
                            dkim1_verified = True, 
                            dkim2_verified = True, ), )
                    ],
                next_cursor = 'eyJsYXN0RG9tYWluIjoiZXhhbXBsZS5jb20ifQ'
            )
        else:
            return DomainListResponse(
                domains = [
                    goodsender.models.domain.Domain(
                        domain = 'example.com', 
                        tracking = 'track.example.com', 
                        return_path = 'bounces.example.com', 
                        require_tls = True, 
                        verification = goodsender.models.domain_verification.DomainVerification(
                            verified = True, 
                            tracking_verified = True, 
                            return_path_verified = True, 
                            dkim1_verified = True, 
                            dkim2_verified = True, ), )
                    ],
        )
        """

    def testDomainListResponse(self):
        """Test DomainListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
