# coding: utf-8

# flake8: noqa

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "DomainsApi",
    "EmailsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Address",
    "Attachment",
    "ConsentEmailEntry",
    "ConsentEmailRecipient",
    "ConsentEmailRequest",
    "ConsentEmailResult",
    "Domain",
    "DomainListResponse",
    "DomainVerification",
    "EmailAccount",
    "EmailListResponse",
    "ErrorResponse",
    "QuotaExceededError",
    "SendEmail",
    "SendEmailErrorResponse",
    "SendEmailRequest",
    "SendEmailResponse",
    "TemplateEmailRequest",
    "TemplateEmailRequestTemplate",
    "TemplateEmailResponse",
    "TrackingSettings",
]

# import apis into sdk package
from goodsender.api.domains_api import DomainsApi as DomainsApi
from goodsender.api.emails_api import EmailsApi as EmailsApi

# import ApiClient
from goodsender.api_response import ApiResponse as ApiResponse
from goodsender.api_client import ApiClient as ApiClient
from goodsender.configuration import Configuration as Configuration
from goodsender.exceptions import OpenApiException as OpenApiException
from goodsender.exceptions import ApiTypeError as ApiTypeError
from goodsender.exceptions import ApiValueError as ApiValueError
from goodsender.exceptions import ApiKeyError as ApiKeyError
from goodsender.exceptions import ApiAttributeError as ApiAttributeError
from goodsender.exceptions import ApiException as ApiException

# import models into sdk package
from goodsender.models.address import Address as Address
from goodsender.models.attachment import Attachment as Attachment
from goodsender.models.consent_email_entry import ConsentEmailEntry as ConsentEmailEntry
from goodsender.models.consent_email_recipient import ConsentEmailRecipient as ConsentEmailRecipient
from goodsender.models.consent_email_request import ConsentEmailRequest as ConsentEmailRequest
from goodsender.models.consent_email_result import ConsentEmailResult as ConsentEmailResult
from goodsender.models.domain import Domain as Domain
from goodsender.models.domain_list_response import DomainListResponse as DomainListResponse
from goodsender.models.domain_verification import DomainVerification as DomainVerification
from goodsender.models.email_account import EmailAccount as EmailAccount
from goodsender.models.email_list_response import EmailListResponse as EmailListResponse
from goodsender.models.error_response import ErrorResponse as ErrorResponse
from goodsender.models.quota_exceeded_error import QuotaExceededError as QuotaExceededError
from goodsender.models.send_email import SendEmail as SendEmail
from goodsender.models.send_email_error_response import SendEmailErrorResponse as SendEmailErrorResponse
from goodsender.models.send_email_request import SendEmailRequest as SendEmailRequest
from goodsender.models.send_email_response import SendEmailResponse as SendEmailResponse
from goodsender.models.template_email_request import TemplateEmailRequest as TemplateEmailRequest
from goodsender.models.template_email_request_template import TemplateEmailRequestTemplate as TemplateEmailRequestTemplate
from goodsender.models.template_email_response import TemplateEmailResponse as TemplateEmailResponse
from goodsender.models.tracking_settings import TrackingSettings as TrackingSettings

