"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "goodsender"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Goodsender API",
    author="Goodsender Support",
    author_email="support@goodsender.com",
    url="https://github.com/good-sender/python-sdk",
    keywords=["OpenAPI", "OpenAPI-Generator", "Goodsender API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Goodsender API. ### Authorization  All API requests require an API key in the &#x60;Authorization&#x60; header:  &#x60;&#x60;&#x60; Authorization: Bearer &lt;your-api-key&gt; &#x60;&#x60;&#x60; 
    """,  # noqa: E501
    package_data={"goodsender": ["py.typed"]},
)
