# coding: utf-8

# flake8: noqa
"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from goodsender.models.address import Address
from goodsender.models.attachment import Attachment
from goodsender.models.consent_email_entry import ConsentEmailEntry
from goodsender.models.consent_email_recipient import ConsentEmailRecipient
from goodsender.models.consent_email_request import ConsentEmailRequest
from goodsender.models.consent_email_result import ConsentEmailResult
from goodsender.models.domain import Domain
from goodsender.models.domain_list_response import DomainListResponse
from goodsender.models.domain_verification import DomainVerification
from goodsender.models.email_account import EmailAccount
from goodsender.models.email_list_response import EmailListResponse
from goodsender.models.error_response import ErrorResponse
from goodsender.models.quota_exceeded_error import QuotaExceededError
from goodsender.models.send_email import SendEmail
from goodsender.models.send_email_error_response import SendEmailErrorResponse
from goodsender.models.send_email_request import SendEmailRequest
from goodsender.models.send_email_response import SendEmailResponse
from goodsender.models.template_email_request import TemplateEmailRequest
from goodsender.models.template_email_request_template import TemplateEmailRequestTemplate
from goodsender.models.template_email_response import TemplateEmailResponse
from goodsender.models.tracking_settings import TrackingSettings

