# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from goodsender.models.address import Address
from goodsender.models.attachment import Attachment
from goodsender.models.tracking_settings import TrackingSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendEmail(BaseModel):
    """
    Must provide valid sender and subject. At least one recipient (from 'to', 'cc', or 'bcc') is required. Either 'text_content', 'html_content', 'markdown_content', or 'template_id' is required. When 'markdown_content' is provided, 'text_content' and 'html_content' are ignored. 
    """ # noqa: E501
    var_from: Address = Field(description="Sender address (required)", alias="from")
    to: List[Address] = Field(description="To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.")
    subject: StrictStr = Field(description="The subject of the email (required)")
    text_content: Optional[StrictStr] = Field(default=None, description="Plain text content")
    html_content: Optional[StrictStr] = Field(default=None, description="HTML content")
    markdown_content: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. ")
    template_id: Optional[StrictStr] = Field(default=None, description="Template ID for templated emails")
    template_data: Optional[Dict[str, Any]] = Field(default=None, description="Data to populate template variables")
    attachments: Optional[List[Attachment]] = Field(default=None, description="Email attachments")
    headers: Optional[Dict[str, StrictStr]] = Field(default=None, description="Custom email headers")
    reply_to: Optional[Address] = Field(default=None, description="Reply-to address")
    send_time: Optional[StrictInt] = Field(default=None, description="Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.")
    webhook_data: Optional[Dict[str, StrictStr]] = Field(default=None, description="Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.")
    tag: Optional[StrictStr] = Field(default=None, description="Custom tag for tracking. Maximum 100 characters.")
    tracking: Optional[TrackingSettings] = Field(default=None, description="Email tracking settings")
    __properties: ClassVar[List[str]] = ["from", "to", "subject", "text_content", "html_content", "markdown_content", "template_id", "template_data", "attachments", "headers", "reply_to", "send_time", "webhook_data", "tag", "tracking"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendEmail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_from
        if self.var_from:
            _dict['from'] = self.var_from.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in to (list)
        _items = []
        if self.to:
            for _item_to in self.to:
                if _item_to:
                    _items.append(_item_to.to_dict())
            _dict['to'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of reply_to
        if self.reply_to:
            _dict['reply_to'] = self.reply_to.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tracking
        if self.tracking:
            _dict['tracking'] = self.tracking.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendEmail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from": Address.from_dict(obj["from"]) if obj.get("from") is not None else None,
            "to": [Address.from_dict(_item) for _item in obj["to"]] if obj.get("to") is not None else None,
            "subject": obj.get("subject") if obj.get("subject") is not None else '',
            "text_content": obj.get("text_content"),
            "html_content": obj.get("html_content"),
            "markdown_content": obj.get("markdown_content"),
            "template_id": obj.get("template_id"),
            "template_data": obj.get("template_data"),
            "attachments": [Attachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "headers": obj.get("headers"),
            "reply_to": Address.from_dict(obj["reply_to"]) if obj.get("reply_to") is not None else None,
            "send_time": obj.get("send_time"),
            "webhook_data": obj.get("webhook_data"),
            "tag": obj.get("tag"),
            "tracking": TrackingSettings.from_dict(obj["tracking"]) if obj.get("tracking") is not None else None
        })
        return _obj


