# coding: utf-8

"""
    Goodsender API

    Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@goodsender.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TrackingSettings(BaseModel):
    """
    Controls email tracking and unsubscribe settings
    """ # noqa: E501
    opens: Optional[StrictBool] = Field(default=None, description="Whether to track email opens")
    clicks: Optional[StrictBool] = Field(default=None, description="Whether to track link clicks")
    unsubscribes: Optional[StrictBool] = Field(default=None, description="Whether to track unsubscribes")
    unsubscribe_group_id: Optional[StrictInt] = Field(default=None, description="Optional unsubscribe group ID. If not specified, uses global unsubscribe list. This setting is ignored if unsubscribes is false.")
    __properties: ClassVar[List[str]] = ["opens", "clicks", "unsubscribes", "unsubscribe_group_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrackingSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if unsubscribe_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.unsubscribe_group_id is None and "unsubscribe_group_id" in self.model_fields_set:
            _dict['unsubscribe_group_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrackingSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "opens": obj.get("opens"),
            "clicks": obj.get("clicks"),
            "unsubscribes": obj.get("unsubscribes"),
            "unsubscribe_group_id": obj.get("unsubscribe_group_id")
        })
        return _obj


